definitions:
  common.I18nCode:
    enum:
    - INTERNAL_SERVER_ERROR
    - BAD_REQUEST
    - UNAUTHORIZED
    type: string
    x-enum-varnames:
    - CodeInternalServerError
    - CodeBadRequestError
    - CodeUnauthorizedError
  common.appError:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/common.I18nCode'
        description: Client error code (i18n key)
      message:
        type: string
      status:
        type: integer
    type: object
  common.appResponse:
    properties:
      data: {}
      status:
        type: integer
    type: object
  dto.UserRegistrationInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      pwdHint:
        type: string
    required:
    - email
    - name
    - password
    type: object
info:
  contact:
    name: Keychi Team
    url: https://github.com/dynonguyen/keychi
  description: Keychi | The best password manager for securely storing, managing data
    such as passwords, passkeys, OTP and credit cards.
  title: Keychi API
  version: "1.0"
paths:
  /admin/health-check:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.appResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/common.appError'
      security:
      - Bearer: []
      summary: Health check
      tags:
      - Admin
  /user:
    post:
      description: Register a new user
      parameters:
      - description: User registration input
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegistrationInput'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/common.appResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.appError'
      summary: Register a new user
      tags:
      - User
schemes:
- http
- https
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: Manage services, health check and other admin tasks.
  name: Admin
- description: Manage user account, authentication and authorization.
  name: User
