CREATE TABLE IF NOT EXISTS users (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	avatar VARCHAR(512),
	pwd_hint VARCHAR(512),

	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS folders (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id INTEGER NOT NULL,

	name VARCHAR(255) NOT NULL,
	icon VARCHAR(255),
	color VARCHAR(24),

	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_folder_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS vaults (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id INTEGER NOT NULL,
	folder_id INTEGER,

	name VARCHAR(512) NOT NULL,
	type VARCHAR(10) NOT NULL,
	custom_fields JSONB DEFAULT '[]'::jsonb,
	properties JSONB DEFAULT '{}'::jsonb,
	note VARCHAR(1024),
	deleted BOOLEAN NOT NULL DEFAULT FALSE,
	update_histories JSONB DEFAULT '[]'::jsonb,

	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_vault_folder FOREIGN KEY (folder_id) REFERENCES folders(id) ON DELETE SET NULL,
	CONSTRAINT fk_vault_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS devices (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id INTEGER NOT NULL,

	name VARCHAR(255) NOT NULL,
	platform VARCHAR(128) NOT NULL,
	ipv4 VARCHAR(32),
	active BOOLEAN DEFAULT TRUE,
	logged_at TIMESTAMP,

	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_device_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS preferences (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id INTEGER NOT NULL,

	theme VARCHAR(10) NOT NULL DEFAULT 'system',
	vault_timeout INTEGER NOT NULL DEFAULT 0,
	vault_timeout_action VARCHAR(10) NOT NULL DEFAULT 'lock',
	language VARCHAR(3) NOT NULL DEFAULT 'en',
	kdf_salt CHAR(16) NOT NULL,
	kdf_algorithm VARCHAR(10) NOT NULL DEFAULT 'pbkdf2',
	kdf_iterations INTEGER NOT NULL DEFAULT 600000,
	kdf_memory INTEGER,
	kdf_parallelism INTEGER,

	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_preferences_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS keys (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id INTEGER NOT NULL,

	api_keys JSONB DEFAULT '[]'::jsonb,
	pin VARCHAR(24),

	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_key_user FOREIGN KEY (user_id) REFERENCES users(id)
);